Call `chdir` on `Dir` instead of main Object
The main Object doesn't have a `chdir` method so using

```
chdir APP_ROOT do
  ...
end
```

results in an error:

```
undefined method `chdir' for main:Object (NoMethodError)
```

Calling `chdir` on `Dir` fixes the issues.