Use STDIN.gets instead of gets in rake task
This is because rake overwrites $stdin and otherwise we see this
error: Errno::ENOENT: No such file or directory @ rb_sysopen

More info: https://stackoverflow.com/a/40643667